# Daily Briefing Workflow
# Morning routine orchestrated by Taipm Agent

name: daily-briefing
description: Generate personalized morning briefing
version: 1.0

# Trigger conditions
triggers:
  - type: command
    pattern: ["daily", "morning", "buổi sáng", "*briefing"]

  - type: scheduled
    cron: "0 9 * * *"  # 9:00 AM daily
    enabled: false  # Enable when automation ready

# Input parameters
inputs:
  date:
    type: string
    default: "{today}"
    description: Date for briefing

  include_sections:
    type: array
    default: [context, tasks, priorities, insights, recommendations]
    description: Sections to include in briefing

# Pre-conditions
pre_conditions:
  - check: memory_available
    description: Memory system accessible

# Main workflow steps
steps:
  # Step 1: Load Context
  - id: load_context
    name: Load Current Context
    actions:
      - action: read_file
        path: ../../memory/context.md
        output: current_context

      - action: read_file
        path: ../../memory/insights.md
        output: recent_insights

      - action: read_file
        path: ../../memory/preferences.yaml
        output: preferences

  # Step 2: Gather Task Information
  - id: gather_tasks
    name: Gather Pending Tasks
    depends_on: [load_context]
    actions:
      - action: extract_tasks
        from: "{current_context}"
        output: pending_tasks

      - action: check_deadlines
        tasks: "{pending_tasks}"
        output: urgent_tasks

      - action: prioritize_tasks
        tasks: "{pending_tasks}"
        by: [urgency, importance, dependencies]
        output: prioritized_tasks

  # Step 3: Analyze Patterns
  - id: analyze_patterns
    name: Analyze Work Patterns
    depends_on: [load_context]
    actions:
      - action: read_file
        path: memory/learning.md
        output: learning_data

      - action: analyze_recent_activity
        context: "{current_context}"
        learning: "{learning_data}"
        window: 7  # Last 7 days
        output: activity_analysis

  # Step 4: Generate Recommendations
  - id: generate_recommendations
    name: Generate Smart Recommendations
    depends_on: [gather_tasks, analyze_patterns]
    actions:
      - action: identify_blockers
        tasks: "{prioritized_tasks}"
        output: blockers

      - action: suggest_focus
        tasks: "{prioritized_tasks}"
        patterns: "{activity_analysis}"
        time_available: "{preferences.work_patterns.active_hours}"
        output: focus_suggestions

      - action: identify_opportunities
        insights: "{recent_insights}"
        patterns: "{activity_analysis}"
        output: opportunities

  # Step 5: Compile Briefing
  - id: compile_briefing
    name: Compile Daily Briefing
    depends_on: [generate_recommendations]
    actions:
      - action: compile_template
        template: |
          # 🧠 Daily Briefing - {{date}}

          ## 📊 Current Context
          **Project:** {{current_context.active_project}}
          **Phase:** {{current_context.phase}}
          **Last Session:** {{current_context.last_session}}

          ---

          ## ✅ Today's Priorities

          {{#each prioritized_tasks limit=5}}
          {{@index}}. **{{this.title}}** - {{this.priority}}
             {{#if this.deadline}}⏰ Deadline: {{this.deadline}}{{/if}}
          {{/each}}

          {{#if urgent_tasks}}
          ### ⚠️ Urgent Items
          {{#each urgent_tasks}}
          - {{this.title}} (Due: {{this.deadline}})
          {{/each}}
          {{/if}}

          ---

          ## 💡 Recommendations

          ### Focus Today
          {{#each focus_suggestions}}
          - {{this}}
          {{/each}}

          ### Blockers to Address
          {{#each blockers}}
          - {{this.description}} → {{this.suggestion}}
          {{/each}}

          {{#if opportunities}}
          ### Opportunities
          {{#each opportunities}}
          - {{this}}
          {{/each}}
          {{/if}}

          ---

          ## 📈 Recent Insights
          {{#each recent_insights limit=3}}
          - **{{this.type}}:** {{this.summary}}
          {{/each}}

          ---

          ## 🎯 Quick Actions

          | Action | Command |
          |--------|---------|
          | Start top task | `*start:1` |
          | Review code | `/microai:go-review-linus` |
          | Deep analysis | `/microai:deep-thinking` |
          | Create content | `/microai:audiobook <url>` |

          ---

          *Generated by Taipm Agent at {{timestamp}}*
        data:
          date: "{date}"
          current_context: "{current_context}"
          prioritized_tasks: "{prioritized_tasks}"
          urgent_tasks: "{urgent_tasks}"
          focus_suggestions: "{focus_suggestions}"
          blockers: "{blockers}"
          opportunities: "{opportunities}"
          recent_insights: "{recent_insights}"
          timestamp: "{now}"
        output: briefing_content

  # Step 6: Deliver and Log
  - id: deliver_briefing
    name: Deliver Briefing
    depends_on: [compile_briefing]
    actions:
      - action: display_to_user
        content: "{briefing_content}"

      - action: log_briefing
        content: "{briefing_content}"
        to: "output/daily/{{date}}/briefing.md"

      - action: update_context
        updates:
          last_briefing: "{date}"
          briefing_delivered: true
        to: ../../memory/context.md

# Post-workflow
post_actions:
  - action: schedule_check_in
    time: "14:00"
    message: "Mid-day check: Tiến độ với priorities hôm nay?"
    enabled: "{preferences.proactivity.reminders} != 'none'"

# Observer commands
observer_commands:
  - "*expand:<section>": Expand a section with more detail
  - "*skip": Skip briefing today
  - "*reschedule:<time>": Reschedule briefing
  - "*tasks": Show full task list
